language: go

go:
  - 1.8
  - 1.9
  - "1.10"

services:
  - docker

before_install:
  - docker pull deangiberson/aws-dynamodb-local
  - docker pull dlsniper/kinesalite

install: make get
script: make travis-integration
